SAcademy/Models/Thematic.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SAcademy.Models
{
    public class Thematic
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string? Id { get; set; }
        public string? Title { get; set; }
        public string? ColorTitle { get; set; }
        public string? Background { get; set; }
        public string? Description { get; set; }
        public string? Certification { get; set; }
        public string? Presentation { get; set; }
        public string? Competences { get; set; }
        public string? Programme { get; set; }
        public string? Prerequis { get; set; }
        public string? Price { get; set; }
        public string? TypeId { get; set; }
        public FType? Type { get; set; }
        public ICollection<Formation>? Formations { get; set; }
    }
}

SAcademy/Controllers/ThematicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using SAcademy.Data;
using SAcademy.Models;

namespace SAcademy.Controllers
{
    
    public class ThematicsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ThematicsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Thematics
        //public async Task<IActionResult> Index()
        //{
        //      return View(await _context.Thematics.ToListAsync());
        //}
        public async Task<IActionResult> ThematicsApi()
        {
            var tematic = await _context.Thematics.Include(x => x.Formations).ToListAsync();
            return Ok(tematic);
        }

        // GET: Thematics/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Thematics == null)
            {
                return NotFound();
            }

            var thematic = await _context.Thematics
                .Include(f => f.Formations)
                    .ThenInclude(x => x.Mode)
                .Include(f => f.Formations)
                    .ThenInclude(x => x.Ville)
                .FirstOrDefaultAsync(f => f.Id == id);
            if (thematic == null)
            {
                return NotFound();
            }

            TempData["idTheme"] = id;
            TempData["FormationCount"] = _context.Formations.Count();

            return View(thematic);
        }

        [Authorize(Roles = "Admin")]
        // GET: Thematics/Create
        public IActionResult Create()
        {
            //ViewData["TypeId"] = new SelectList(_context.FTypes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ColorTitle,Background,Description,Certification,Presentation,Competences,Programme,Prerequis,Price,TypeId")] Thematic thematic)
        {
            if (ModelState.IsValid)
            {
                _context.Add(thematic);
                await _context.SaveChangesAsync();
                return RedirectToAction("ThematicDetail", "FormationPages");
            }
            //ViewData["TypeId"] = new SelectList(_context.FTypes, "Id", "Name", thematic.TypeId);

            return View(thematic);
        }

        [Authorize(Roles = "Admin")]
        // GET: Thematics/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Thematics == null)
            {
                return NotFound();
            }

            var thematic = await _context.Thematics.FindAsync(id);
            if (thematic == null)
            {
                return NotFound();
            }
            ViewData["TypeId"] = new SelectList(_context.FTypes, "Id", "Name", thematic.TypeId);

            return View(thematic);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,ColorTitle,Background,Description,Certification,Presentation,Competences,Programme,Prerequis,Price,TypeId")] Thematic thematic)
        {
            if (id != thematic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(thematic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThematicExists(thematic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ThematicDetail", "FormationPages");
            }

            ViewData["TypeId"] = new SelectList(_context.FTypes, "Id", "Name", thematic.TypeId);

            return View(thematic);
        }

        [Authorize(Roles = "Admin")]
        // GET: Thematics/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Thematics == null)
            {
                return NotFound();
            }

            var thematic = await _context.Thematics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (thematic == null)
            {
                return NotFound();
            }

            return View(thematic);
        }

        // POST: Thematics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Thematics == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Thematics'  is null.");
            }
            var thematic = await _context.Thematics.FindAsync(id);
            if (thematic != null)
            {
                _context.Thematics.Remove(thematic);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("ThematicDetail", "FormationPages");
        }

        private bool ThematicExists(string id)
        {
          return _context.Thematics.Any(e => e.Id == id);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetRegisters()
        {
            return View(_context.ThemeInscrits.ToList());
        }

        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(ThemeInscrit themeInscrit)
        {
            if (ModelState.IsValid)
            {
                var addinscrit = new ThemeInscrit
                {
                    FullName = themeInscrit.FullName,
                    Email = themeInscrit.Email,
                    Phone = themeInscrit.Phone,
                    ThematicName = themeInscrit.ThematicName
                };
                _context.Add(addinscrit);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Home");
        }
        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteregisterTheme(string id)
        {
            var resId = _context.ThemeInscrits.FirstOrDefault(a => a.Id == id);
            _context.Remove(resId);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GetRegisters));

        }
    }
}

SAcademy/Views/Thematics/Delete.cshtml
@model SAcademy.Models.Thematic

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Thematic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ColorTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ColorTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Background)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Background)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SAcademy/Views/Thematics/Details.cshtml
@model SAcademy.Models.Thematic

@{
    ViewData["Title"] = "Details";
    string? cityMode = null;
    string? mode = null;
}
<style>
    .navtheme {
        width: 92%;
    }

    .allerA {
        font-size: 1.5em;
        font-weight: bold;
        color: black;
    }

    .navThemeitem {
        font-size: 2em;
        font-weight: bold;
        color: black !important;
        text-decoration: none !important;
    }

    article {
        padding: 1.5em 2em 4em 2em;
        margin: 1em;
    }

    .bar {
        width: 30px;
        height: 5px;
        background: #ce0033;
        margin-right: .5em;
    }

    .btnSession {
        background: #ce0033;
        color: white;
        font-weight: bold;
        text-transform: uppercase;
        margin: 1em 0 1em 0;
    }

    .pls {
        font-weight: bold;
        font-size: 2em;
    }

    .faqs-item {
        width: 100%;
        margin: 0 0 20px 0;
        padding: 0;
        display: block;
    }

    .faqs-title {
        color:black;
        display: flex;
        position: relative;
        font-size: 1.5rem;
        font-weight: bold;
        text-decoration: none !important;
        padding: 20px;
        width: 100%;
        outline: none;
        transition: 0.4s;
    }

    .faqs-title:hover {
        color: black;
    }

        .faqs-title:after {
            content: '\002B';
            font-weight: bold;
            float: right;
            margin-left: auto;
            font-size: 35px;
            line-height: 1;
            padding-left: 20px;
        }

    .active:after {
        content: "\2212";
    }

    .faqs-content {
        padding: 0;
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.2s ease-out;
    }

    .faqs-content-inside {
        padding: 20px;
    }
</style>
<div class="yeld mb-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent pl-5">
            <li class="breadcrumb-item text-center pl-2"><a href="/"><img class="w-75" src="~/img/home.png"></a></li>
            <li class="breadcrumb-item active" style="font-size:20px;" aria-current="page">Détails</li>
        </ol>
    </nav>
    <div class="m-auto" style="width:70%;">
        <h2 class="pt-4 pb-2" style="color:#ce0033; font-weight:bold; margin-left:0.5em;">@Model.Title</h2>
        <article class="border border-1" style="width:96.6%;">
            <p class="allerA">Aller à</p>
            <div class="d-flex justify-content-between navtheme">
                <div class="d-flex align-items-center ">
                    <span class="bar"></span>
                    <a class="navThemeitem" href="#presentation">Présentation</a>
                </div>
                <div class="d-flex align-items-center ">
                    <span class="bar"></span>
                    <a class="navThemeitem" href="#competences">Compétences</a>
                </div>
                <div class="d-flex align-items-center ">
                    <span class="bar"></span>
                    <a class="navThemeitem" href="#prerequis">Prérequis</a>
                </div>
            </div>
            @*<a href="/formations" class="float-right btn btn-danger btnSession" >Les Sessions Ouvertes</a>*@
            <button class="float-right btn btn-danger btnSession" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="margin-right:3.2em;" >
                Les Sessions Ouvertes
            </button>
        </article>
            
        <div class="collapse" id="collapseExample">
            <div class="card card-body text-center" style="margin:0 1em; width:96.6%;">
                <div class="d-md-flex justify-content-between align-items-center" style="width:90%; margin:auto;">
                    <p class="fon-weight-bold pt-2 font-weight-bold">Totale de formations : @Model.Formations.Count() / @TempData["FormationCount"]</p>
                    <a href="/formations" class="btn text-light font-weight-bold btnSession" style="width:20%; background:black;">Nos Formations</a>
                </div>
                @if(Model.Formations.Count > 0)
                {
                    
                    @foreach(var f in Model.Formations)
                    {
                        string? inscrButtonbg = f.OffreFBgColorButton;
                        var size = string.Concat(f.OffreFSize, "px");

                        if (f.Mode.Name == "Distanciel")
                        {
                            mode = "";
                            cityMode = "Distanciel";
                        }
                        else
                        {
                            mode = f.Mode.Name;
                            cityMode = f.Ville.Name;
                        }
                        <div class="mb-3">
                            <div class="card card-body formation m-auto" style="width:90%;background:@f.OffreFBgColor !important;">
                                <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
                                    <div class="mr-2 mb-3 mb-lg-0 text-center">
                                        <div class="d-flex align-items-center text-center">
                                            <img class="fmrImg mr-1" src="/img/agenda.png" style="width:3.3vw; margin-left:5px;" />
                                            <div class="pt-3" style="margin-left:6px;">
                                                <p class="w-100"> Du @Html.DisplayFor(modelItem => f.StartDay)</p>
                                                <p class="w-100"> Au @Html.DisplayFor(modelItem => f.EndDay)</p>
                                            </div>
                                        </div>
                                        <div class="d-flex justify-content-center align-items-center">
                                            <img class="fmrImg mr-1" src="/img/time.png" style="width:4vw;" />
                                            <h6 class="pt-3">@Html.DisplayFor(modelItem => f.StartTime) => @Html.DisplayFor(modelItem => f.EndTime)</h6>
                                        </div>
                                        <div class="d-flex align-items-center" style="margin-left:8px;">
                                            <img class="fmrImg" src="/img/icons/price.png" style="width:3vw;"/>
                                            <h6 class="pt-3 ml-3">@f.Price</h6>
                                        </div>
                                    </div>

                                    <div class="media-body text-center">
                                        <h5 class="font-weight-bold" style="color:@f.OffreFColor;font-size:@size;">@f.Title</h5>
                                        <p class="descFormation">@f.Description</p>
                                        <h5 style="color:#ce0033;"><span class="text-muted"><img style="width:5%;" src="/img/local.png"><br /></span>@cityMode</h5>
                                        <img class="fmrImg" src="/img/iconForm1.png" style="width:2vw;" />
                                        <img class="fmrImg" src="/img/iconForm2.png" style="width:2vw;" />
                                        <img class="fmrImg" src="/img/iconForm4.png" style="width:2vw;" />
                                    </div>

                                    <div class="mt-3 mt-lg-0 ml-lg-3 text-center p-2 formation-3">
                                        <img class="fmrImg" src="/img/iconForm3.png" style="width:3em;" />
                                        <h5>@Model.Title</h5>
                                        <p>@mode</p>
                                        @if (f.Status == true) {
                                            <a href="/formations/details/@f.Id" class="inscription" style="background:@inscrButtonbg;">Inscription</a>
                                        } else {
                                            <p class="text-light m-auto font-weight-bold" style="width:59%; background:@inscrButtonbg; padding:0.2em;">Terminé</p>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="p-3 m-auto d-flex justify-content-center align-items-center formation" style="height:25vh; width:90%;">
                        <h5>Aucune formation de prévu actuellement, restez informés via nos réseaux!</h5>
                    </div>
                }
            </div>
        </div>

        
        <div class="faqs-grid">

            <div class="faqs-item ">

                <a class="faqs-title d-flex align-items-center" href="#custom">
                    <img style="width:60px;" src="~/img/presentation.svg" />
                    Presentation
                </a>


                <div class="faqs-content">
                    <div class="faqs-content-inside">

                        <p>
                            @Html.Raw(Model.Presentation)
                        </p>

                    </div>
                </div>
            </div>

            <div class="faqs-item " id="competences">

                <a class="faqs-title d-flex align-items-center" href="#custom">
                    <img style="width:65px;" src="~/img/iconForm1.png" />
                    Compétences visées
                </a>


                <div class="faqs-content">
                    <div class="faqs-content-inside">

                        <p>@Html.Raw(Model.Competences)</p>
                    </div>
                </div>
            </div>

            <div class="faqs-item ">

                <a class="faqs-title d-flex align-items-center" href="#custom">
                    <img style="width:65px;" src="~/img/iconForm8.png" />
                    Programme
                </a>


                <div class="faqs-content">
                    <div class="faqs-content-inside">
                        <p>@Html.Raw(Model.Programme)</p>
                    </div>
                </div>
            </div>

            <div class="faqs-item " id="prerequis">

                <a class="faqs-title d-flex align-items-center" href="#custom">
                    <img style="width:65px;" src="~/img/iconForm7.png" />
                    Prérequis
                </a>


                <div class="faqs-content">
                    <div class="faqs-content-inside">
                        <p>@Html.Raw(Model.Prerequis)</p>
                    </div>
                </div>
            </div>
            <div class="faqs-item ">

                <a class="faqs-title d-flex align-items-center" href="#custom">
                    <img style="width:65px;" src="~/img/iconForm2.png" />
                    Modalités
                </a>


                <div class="faqs-content">
                    <div class="faqs-content-inside">
                        <p>@Html.Raw(Model.Price)</p>
                    </div>
                </div>
            </div>
            <a href="/formations" class="btn btn-danger btnSession ml-4" style="width:20%;">Nos Formations</a>

        </div>
    </div>

</div>







<script>
    var acc = document.getElementsByClassName('faqs-title');
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener('click', function () {
            this.classList.toggle('active');
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + 'px';
            }
        });
    }


</script>

SAcademy/Views/Thematics/GetRegisters.cshtml
@model IEnumerable<SAcademy.Models.ThemeInscrit>

@{
    Layout = "_LayoutDashboard";

}

<h1>GetRegisters</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThematicName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThematicName)
            </td>
            <td>
                <form style="display:inline;" method="post" asp-controller="Thematics" asp-action="DeleteregisterTheme">
                    <input type="hidden" name="Id" value="@item.Id" />
                    <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>